/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examples;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;


/**
 *
 * @author jeffe
 */
public class Inseminação extends javax.swing.JFrame {
    private static Connection conn;
    private static ResultSet rs;
    private static Statement stmt;
    private String dbUrl;
    private Date data;
    private SimpleDateFormat sdf;
    /**
     * Creates new form Inseminação
     */
    public Inseminação() {
        super("Inseminação");
        initComponents();
        this.setVisible(true);
        data = new Date();
        sdf = new SimpleDateFormat("dd/MM/yyyy");
        jTextField2.setText(sdf.format(data));
        jTextField4.setText("11/11/1111");
        carregarID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("checked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Número do animal:");
        jLabel1.setToolTipText("Digite a ID do animal.");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Data da inseminação:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Touro:");
        jLabel3.setToolTipText("Coloque o nome do touro.");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Resultado:");

        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Alterar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Limpar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sem diagnóstico", "Prenha", "Vazia" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Data do diagnóstico:");

        jLabel6.setText("Ano da estação:");

        jLabel7.setText("Tentativa:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));

        jLabel8.setText("ID:");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField1)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField5)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        jTextField3.requestFocus();
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        if(confirmarOperacao("localizar última inseminação"
                + " desta vaca para diagnóstico?")==true){
            buscarDiagnostico();
        }else{
            jComboBox1.requestFocus();
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        jTextField4.requestFocus();
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             if(verificarCampos()==true){
                 if(verificarAnimalExiste(Integer.parseInt(jTextField1.getText()))==true){
                     try{
                        abrirBanco();
                        stmt.executeUpdate
                        (
                            "INSERT INTO Inseminacoes" +
                            "(idInseminacoes, animais_idanimal, tentativa, ano,"
                                    + "data_inseminacao, touro, data_diagnostico, diagnostico)" +
                            "VALUES('"+ Integer.parseInt(jTextField6.getText()) + "','" +
                                    Integer.parseInt(jTextField1.getText())+ "','" +
                                    (String)(jComboBox1.getSelectedItem()) + "','" +
                                    jTextField5.getText()+ "','" +
                                    formatarData(jTextField2.getText())+ "','" +
                                    jTextField3.getText()+ "','" +
                                    formatarData(jTextField4.getText())+ "','" +
                                    (String)(jComboBox2.getSelectedItem()) + "')"
                        );
                        String s = "ao gravar.";
                        informarSucesso(s);
                    }catch(Exception err){
                        fecharBanco();
                        JOptionPane.showMessageDialog(null,"Falha"+err, "Atenção",
                                JOptionPane.ERROR_MESSAGE);
                    }
                    fecharBanco();
                    limparCampos();
                 }else{
                     JOptionPane.showMessageDialog(null, "Inconsistência verifique"
                             + " se a vaca está cadastrada corretamente", "Atenção",
                             JOptionPane.ERROR_MESSAGE);
                 }
        }else{
            JOptionPane.showMessageDialog(null,"Verifique os campos", "Atenção",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        buscar();
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        buscar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(confirmarOperacao("excluir?")==true){
            try{
                    abrirBanco();
                    int id = Integer.parseInt(jTextField6.getText());
                    stmt.executeUpdate
                    (
                            "DELETE FROM inseminacoes " +
                            "WHERE idInseminacoes =" +
                            id
                    );
                    String s = "excluir este registro.";	
                    informarSucesso(s);
                    limparCampos();
            }catch(Exception err){
                    fecharBanco();
                    JOptionPane.showMessageDialog(null,
                            "Falha na tentativa de \n excluir esta inseminação:\n"+err,
                            "Atenção", JOptionPane.ERROR_MESSAGE);
            }
            fecharBanco();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        limparCampos();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       if(verificarCampos()==true){
           if(verificarAnimalExiste(Integer.parseInt(jTextField1.getText()))==true){
               if(compararDatas()==true){
                    try{
                         abrirBanco();
                         stmt.executeUpdate
                         (
                              "UPDATE inseminacoes SET " +
                              "animais_idanimal ='" + Integer.parseInt(jTextField1.getText()) + 
                              "',tentativa ='" + (String)(jComboBox1.getSelectedItem()) +
                              "',ano ='" + jTextField5.getText()+
                              "',data_inseminacao ='" + formatarData(jTextField2.getText()) +
                              "',touro ='" + jTextField3.getText() +   
                              "',data_diagnostico ='" + formatarData(jTextField4.getText()) +
                              "',diagnostico ='" + (String)(jComboBox2.getSelectedItem()) +      
                              "'WHERE idInseminacoes =" +
                              Integer.parseInt(jTextField6.getText())
                         );
                         String s = "alterar.";
                         informarSucesso(s);
                         limparCampos();
                     }catch(Exception err){
                             fecharBanco();
                             JOptionPane.showMessageDialog(null,
                                     "Falha na tentativa de \n alterar esta inseminação:\n"+err,
                                     "Atenção", JOptionPane.ERROR_MESSAGE);

                     }
                     fecharBanco();
               }else{
                   JOptionPane.showMessageDialog(null, "Data incompatíveis",
                           "Atenção", JOptionPane.ERROR_MESSAGE);
               }
           }else{
               JOptionPane.showMessageDialog(null,"Verifique o cadastro deste "
                       + "\n animal. Não se pode modificar o registro de inseminação"
                       + "\n mudando o número da vaca.", "Atenção",
                    JOptionPane.ERROR_MESSAGE);
           }
       }else{
           JOptionPane.showMessageDialog(null,"Verifique os campos", "Atenção",
                    JOptionPane.ERROR_MESSAGE);
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void buscar(){
        try{
            abrirBanco();
            int id = Integer.parseInt(jTextField6.getText());
            rs = stmt.executeQuery 
            (
                "SELECT * FROM inseminacoes"+
                " WHERE idinseminacoes =" +
                id
            );
            rs.next();
            jTextField1.setText(rs.getString("animais_idanimal"));
            jComboBox1.setSelectedItem(rs.getString("tentativa"));
            jTextField5.setText(rs.getString("ano").substring(0,4));
            jTextField2.setText(sdf.format(rs.getDate("data_inseminacao")));
            jTextField3.setText(rs.getString("touro"));
            jTextField4.setText(sdf.format(rs.getDate("data_diagnostico")));
            jComboBox2.setSelectedItem(rs.getString("diagnostico"));
        }catch(Exception err){
                fecharBanco();
                JOptionPane.showMessageDialog(null,
                        "Falha na tentativa de \n buscar esta inseminação:\n"+err,
                        "Atenção", JOptionPane.ERROR_MESSAGE);
        }
        fecharBanco();
    }
    
    private void buscarDiagnostico(){
        try{
            abrirBanco();
            int id = Integer.parseInt(jTextField1.getText());
            rs = stmt.executeQuery 
            (
                "SELECT * FROM inseminacoes"+
                " WHERE animais_idanimal = " +
                id +
                        " ORDER BY data_inseminacao DESC LIMIT 1"
            );
            rs.next();
            jTextField1.setText(rs.getString("animais_idanimal"));
            jComboBox1.setSelectedItem(rs.getString("tentativa"));
            jTextField5.setText(rs.getString("ano").substring(0,4));
            jTextField2.setText(sdf.format(rs.getDate("data_inseminacao")));
            jTextField3.setText(rs.getString("touro"));
            jTextField4.setText(sdf.format(data));
            jTextField6.setText(rs.getString("idinseminacoes"));
            jComboBox2.setSelectedItem(rs.getString("diagnostico"));
        }catch(Exception err){
                fecharBanco();
                JOptionPane.showMessageDialog(null,
                        "Falha na tentativa de \n buscar este animal:\n"+err,
                        "Atenção", JOptionPane.ERROR_MESSAGE);
        }
        fecharBanco();
    }
    
    private boolean compararDatas(){
        boolean boo = true;
        try{
            Date di = sdf.parse(jTextField2.getText());
            Date dg = sdf.parse(jTextField4.getText());
            System.out.println(di);
            System.out.println(dg);
            if(di.after(dg)){
                boo = false;
            }
        }catch(Exception e){
            System.out.println(e);
        }
        System.out.println(boo);
        return boo;
    }
    
    public String formatarData(String d){
        try{
                String ano = d.substring(6,10);
                String mes = d.substring(3,5);
                String dia = d.substring(0,2);
                d = ano + "-" + mes + "-" + dia;
        }catch(Exception err){JOptionPane.showMessageDialog(null,"O campo data está incorreto");}
        return d;
    }
    
    private boolean verificarCampos(){
        boolean b = true;
        if(jTextField1.getText().equals("")){
            b = false;
        }
        if(jTextField2.getText().equals("")){
            b = false;
        }
        if(jTextField3.getText().equals("")){
            b = false;
        }
        if(jTextField4.getText().equals("")){
            b = false;
        }
        if(jTextField5.getText().equals("")){
            b = false;
        }
        if(jTextField6.getText().equals("")){
            b = false;
        }
        return b;
    }
    
    private boolean confirmarOperacao(String operacao){
        Object []opcoes = {"Sim", "Não"};
        boolean b = true;
        int op = JOptionPane.showOptionDialog(null,
                "Deseja " +operacao ,
                "Atenção",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null,
		opcoes, opcoes[0]);		
        if (op == 0) {
                b = true;
        }else{
                b = false;
        }
        return b;
    }
    
    public void abrirBanco() {
		dbUrl = "jdbc:mysql://127.0.0.1/bancopecuaria";
                String user = "root";
                String pass = "root";
		try {
			Class.forName("com.mysql.jdbc.Driver");
			conn = DriverManager.getConnection(dbUrl, user, pass);
			stmt = conn.createStatement();
		} catch (ClassNotFoundException e) {
			JOptionPane.showMessageDialog(null,
			 "Driver não encontrado",
			 "Atenção",
			  JOptionPane.ERROR_MESSAGE);
			  System.exit(0);
		} catch (SQLException sqlE) {
			JOptionPane.showMessageDialog(null,
			 sqlE.getMessage(),
			 "Erro durante conexão com banco de dados",
			  JOptionPane.ERROR_MESSAGE);
			  System.exit(0);
		}
	}
    	public void fecharBanco() {
		try {
			stmt.close();
			conn.close();
		} catch (SQLException sqlE) {
			JOptionPane.showMessageDialog(null,
			 sqlE.getMessage(),
			 "Erro ao fechar a conexão com banco de dados",
			  JOptionPane.ERROR_MESSAGE);
			  System.exit(0);
		}
	}
        
    public void carregarID(){
	String s = "00";
	try{
		int maior = 0, x = 0;
		abrirBanco();
		rs = stmt.executeQuery 
		(
			"SELECT idInseminacoes FROM Inseminacoes"
		);
		while(rs.next()) {
			x = rs.getInt("idInseminacoes");
			if(x>maior) {
				maior = x;
			}
		}
		s = String.valueOf(++maior);
			fecharBanco();
	} catch(Exception err) {
            System.out.println(err);
            fecharBanco();
            s = "01";
	}
	jTextField6.setText(s); 
        jTextField1.requestFocus();
    }
    
    private boolean verificarAnimalExiste(int id){
        boolean b = false;
        abrirBanco();
        try{
            rs = stmt.executeQuery
                    (
                            "SELECT * FROM animais"+
                                    " WHERE idanimal ="+
                                    id
                    );
            if(rs.next()){
                b = true;
            }
            if(rs.getString("sexo").equalsIgnoreCase("FÊMEA")){
                b = true;
            }else{
                b = false;
            }
        }catch(Exception e){
            b = false;
        }
        fecharBanco();
        return b;
    }
        
    private void limparCampos(){
        jTextField1.setText("");
        jTextField2.setText(sdf.format(data));
        jTextField3.setText("");
        jTextField4.setText("11/11/1111");
        jTextField5.setText("");
        jTextField6.setText("");
        carregarID();
    }    
        
    public void informarSucesso(String s){
    JOptionPane.showMessageDialog(null,"Sucesso ao "+ s + ".",
            "Parabéns", JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
